AWSTemplateFormatVersion: '2010-09-09'
Description: deploys roles to create EC2 instances and ECS tasks.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources:
  ############################################
  #####               ROLE               #####
  ############################################
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-ecs-task-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: /
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Path: /
  ############################################
  #####             Profile              #####
  ############################################
  EC2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${EnvironmentName}-instance-profile
      Path: /
      Roles:
        - !Ref EC2Role
Outputs:
  EcsTaskRole:
    Description: A reference to the ECS Task Role
    Value: !Ref EcsTaskRole
    Export:
      Name: !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-task-role
  EC2Profile:
    Description: A reference to the EC2 Profile
    Value: !Ref EC2Profile
    Export:
      Name: !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ec2-profile