AWSTemplateFormatVersion: '2010-09-09'
Description: deploys an Log Group that notes server's loges.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources:
  ############################################
  #####            Log Group             #####
  ############################################
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${EnvironmentName}-log-group
Outputs:
  LogGroup:
    Value: !Ref LogGroup
    Export:
      Name: !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-log-group  