AWSTemplateFormatVersion: '2010-09-09'
Description: deploys Service Discovery that referes container's ip.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources:
  ############################################
  #####        Service Discovery         #####
  ############################################
  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Sub ${EnvironmentName}
      Vpc:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-vpc
Outputs:
  LogGroup:
    Value: !Ref ServiceDiscoveryNamespace
    Export:
      Name: !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-pdn