AWSTemplateFormatVersion: '2010-09-09'
Description: deploys Redis server.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  ClusterSize:
    Description: How many ECS hosts do you want to initially deploy?
    Type: Number
    Default: 1
Resources:
  ############################################
  #####         Task Definition          #####
  ############################################
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      TaskRoleArn:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-task-role
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-task-role
      ContainerDefinitions:
        - Name: redis
          Image: redis:latest
          PortMappings:
            - ContainerPort: 6379
              HostPort: 6379
          MemoryReservation: 512
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue:
                  !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-log-group
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${EnvironmentName}-redis
  ############################################
  #####             Service              #####
  ############################################
  Service:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      DesiredCount: !Ref ClusterSize
      Cluster:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-cluster
      TaskDefinition: !Ref TaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-backend-sg
          Subnets:
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-private-subnet1
  ############################################
  #####        Service Discovery         #####
  ############################################
  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: redis
      DnsConfig:
        DnsRecords: [{Type: A, TTL: "10"}]
        NamespaceId:
          Fn::ImportValue:
            !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-pdn
      HealthCheckCustomConfig:
        FailureThreshold: 1