AWSTemplateFormatVersion: '2010-09-09'
Description: deploys Tomcat server.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  ClusterSize:
    Description: How many ECS hosts do you want to initially deploy?
    Type: Number
    Default: 2
  TomcatTag:
    Description: the Tomcat ECR tag
    Type: String
    Default: 190401
Resources:
  ############################################
  #####         Task Definition          #####
  ############################################
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 1024
      Memory: 8192
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      TaskRoleArn:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-task-role
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-task-role
      ContainerDefinitions:
        - Name: tomcat
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/tomcat:${TomcatTag}
          PortMappings:
            - ContainerPort: 9081
              HostPort: 9081
          MemoryReservation: 2048
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue:
                  !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-log-group
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${EnvironmentName}-tomcat
          Environment:
            - Name: "REDIS_URI"
              Value: !Sub redis.${EnvironmentName}
            - Name: "MYSQL_URI"
              Value: !Sub mysql.${EnvironmentName}
            - Name: "CATALINA_OPTS"
              Value: "-Xms512m -Xmx1024m"
            - Name: "SPRING_PROFILES_ACTIVE"
              Value: "prod"
            - Name: "SPRING_DATASOURCE_URL"
              Value: !Sub jdbc:mysql://mysql.${EnvironmentName}:3306/HOGEHOGE?useUnicode=true&characterEncoding=UTF-8
            - Name: "SPRING_REDIS_HOST"
              Value: !Sub redis.${EnvironmentName}
  ############################################
  #####             Service              #####
  ############################################
  Service:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      DesiredCount: !Ref ClusterSize
      Cluster:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-cluster
      TaskDefinition: !Ref TaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-host-sg
          Subnets:
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-private-subnet1
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-private-subnet2
  ############################################
  #####        Service Discovery         #####
  ############################################
  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: tomcat
      DnsConfig:
        DnsRecords: [{Type: A, TTL: "10"}]
        NamespaceId:
          Fn::ImportValue:
            !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-pdn
      HealthCheckCustomConfig:
        FailureThreshold: 1