AWSTemplateFormatVersion: '2010-09-09'
Description: deploys Nginx server.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  ClusterSize:
    Description: How many ECS hosts do you want to initially deploy?
    Type: Number
    Default: 1
  NginxTag:
    Description: the Nginx ECR tag
    Type: String
    Default: 190419
Resources:
  ############################################
  #####           Target Group           #####
  ############################################
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue:
              !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-default-tg
      LoadBalancerArn:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-loadBalancer
      Port: 80
      Protocol: HTTP
  ECSALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ALBListener
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue:
              !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-default-tg
      Conditions:
        - Field: path-pattern
          Values: [/]
      ListenerArn: !Ref ALBListener
      Priority: 1
  ############################################
  #####         Task Definition          #####
  ############################################
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      TaskRoleArn:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-task-role
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-task-role
      ContainerDefinitions:
        - Name: nginx
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nginx:${NginxTag}
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
          MemoryReservation: 512
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue:
                  !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-log-group
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${EnvironmentName}-nginx
          Environment:
            - Name: "NGINX_SERVER_NAME"
              Value: !Sub tomcat.${EnvironmentName}
            - Name: "NGINX_SERVER_PORT"
              Value: "9081"
  ############################################
  #####             Service              #####
  ############################################
  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSALBListenerRule
    Properties:
      LaunchType: FARGATE
      DesiredCount: !Ref ClusterSize
      Cluster:
        Fn::ImportValue:
          !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-cluster
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-ecs-proxy-sg
          Subnets:
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-private-subnet1
            - Fn::ImportValue:
                !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-private-subnet2
      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: 80
          TargetGroupArn:
            Fn::ImportValue:
              !Sub ${AWS::AccountId}-${AWS::Region}-${EnvironmentName}-default-tg